routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
        Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
        Route::resource('/contacts', 'ContactsController');
        
        Route::get('/batchcreate/{rows}', 'ContactsController@batchCreate')->name('batchcreate');
        Route::post('/batchcreate', 'ContactsController@batchStore')->name('batchcreate');
        
        Route::get('/batchupdate/{id}', 'ContactsController@batchEdit')->name('batchupdate');
        Route::post('/batchupdate', 'ContactsController@batchUpdate')->name('batchupdate');        
        
        Route::delete('/batchdelete', 'ContactsController@batchDelete')->name('batchdelete');
        
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
     /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['created_at', 'updated_at'];
}

app/Http/Controllers/API/contact/v1/ContactsController.php
<?php

namespace App\Http\Controllers\API\contact\v1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\contact\v1\ContactService;
use App\Contact;
use Gate;
class ContactsController extends Controller {

    /**
     * Create protected property 
     * to get contact data
     */
    protected $contacts;

    /**
     * load and init service data
     * for contact service data 
     */
    public function __construct(ContactService $contat) {
        $this->contacts = $contat;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $data = $this->contacts->getContacts();
            return response()->json($data, 200);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $validator = $this->contacts->validate($request->all());

            if ($validator === true) {
                $contacts = $this->contacts->createContact($request->all());
                return response()->json($contacts, 201);
            }
            return $validator;
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $data = $this->contacts->getContact($id);
            return response()->json($data);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $validator = $this->contacts->validate($request->all(), $id, true);
            if ($validator === true) {
                $contacts = $this->contacts->updateContact($request->all(), $id);
                return response()->json($contacts, 201);
            }
            return $validator;
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $this->contacts->deleteContact($id);
            if (!$this->contacts->deleteContact($id)) {
                return response()->json(['success' => 'Data deleted successfuly'], 204);
            }
            return response()->json(['message' => 'Found Problem in deleting'], 500);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Store multiple record newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function batchStore(Request $request) {
        if (Gate::any(['manage-batch-contacts'])) {
            $validator = $this->contacts->batchValidate($request->all());
            if ($validator->fails()) {
                return response()->json(['errors' => $validator->errors()], 401);
            } else {
                $this->contacts->batchCreateContact($request->all());
                return response()->json(['success' => 'Data Has Been Inserted Successfully'], 201);
            }
            return response()->json(['errors' => 'Server Not Found'], 500);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }


    /**
     * batch update resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     * */
    public function batchUpdate(Request $request) {
        if (Gate::any(['manage-batch-contacts'])) {
            $validator = $this->contacts->batchValidate($request->all(), true);
            if ($validator->fails()) {
                return response()->json(['error' => $validator->errors()], 401);
            }
            if ($this->contacts->batchUpdateContact($request->all())) {

                return response()->json(['success' => 'Data Has Been Updated Successfully'], 204);
            } else {
                return response()->json(['errors' => 'Nothing is changed to update'], 500);
            }
            return response()->json(['errors' => 'Server Not Found'], 500);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    public function batchDelete(Request $request) {
        if (Gate::any(['manage-batch-contacts'])) {
            $contactIds = $request->all()['Ids'];
            if ($this->contacts->batchDeleteContact($contactIds)) {
                return response()->json(['success' => 'Data Is Deleted Successfully'], 204);
            } else {
                return response()->json(['error' => 'Deleted Is Not Deleted Successfully'], 401);
            }
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

}

app/Http/Controllers/Admin/ContactsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Contact;
use App\Role;
use Gate;
use App\Services\contact\v1\ContactService;

class ContactsController extends Controller {

    /**
     * Create protected property 
     * to get contact data
     */
    protected $contacts;

    /**
     * load and init service data
     * for contact service data 
     */
    public function __construct(ContactService $contat) {
        $this->contacts = $contat;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $contacts = Contact::paginate(5);
            return view('admin.contact.index')->with('contacts', $contacts)
                            ->with('numOfRow', 1);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            return view('admin.contact.create');
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $validator = $this->contacts->validate($request->all());
            if ($validator === true) {
                $contact = $this->contacts->createContact($request->all());
                session()->flash('success', $request->name . ' Has been Inserted Successfully.');
            }

            session()->flash($validator);
            return $validator;
        }else {
            abort(403, 'Unauthorized action.');
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $roles = Role::all();
            $user = User::find($contact->id);
            $data = [
                'user' => $user,
                'roles' => $roles,
                'contact' => $contact
            ];
            return view('admin.contact.view')->with($data);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $roles = Role::all();
            $data = [
                'roles' => $roles,
                'contact' => $contact
            ];
            return view('admin.contact.edit')->with($data);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $validator = $this->contacts->validate($request->all(),$contact->id, true);
            if($validator === true) {
                $contacts = $this->contacts->updateContact($request->all(), $contact->id);
                session()->flash('success', $contact->name . ' Has Been Updated.');
                return response()->json($contacts, 201);
            }
            session()->flash('error', ' Testing error flash message');
            return $validator;
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact) {
        if (Gate::any(['manage-contacts','manage-batch-contacts'])) {
            $this->contacts->deleteContact($contact->id);
            if (!$this->contacts->deleteContact($contact->id)) {
                session()->flash('success', $contact->name . ' Has Been Deleted Successfully');
                return response()->json(['success' => 'Data deleted successfuly'], 204);
            }
            return response()->json(['error' => 'Found Problem at deleting'], 500);
        }else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Show the form for creating a  batch of new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function batchCreate($numOfRow) {
        if (Gate::allows('manage-batch-contacts')) {
            return view('admin.contact.batchCreate')
                            ->with('numOfRows', $numOfRow);
        }else {
            abort(403, 'Unauthorized action.');
        }               
    }
    
      /**
     * Store multiple record newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function batchStore(Request $request) {
        if (Gate::allows('manage-batch-contacts')) {
            //return $request->all()['contact'];
            $validator = $this->contacts->batchValidate($request->all());
            if ($validator->fails()) {
                return response()->json([ 'errors' =>  $validator->errors() ], 401);
            }else {
            // Contact::insert($request->all()['contact']);
                $this->contacts->batchCreateContact($request->all()['contact']);
                session()->flash('success', 'Data Has Been Inserted Successfully');
                return response()->json(['success' => 'Data Has Been Inserted Successfully'], 201);
            }
            session()->flash('error', 'Testing error flash message');
            return response()->json([ 'errors' =>  'Server Not Found' ], 500);
        }else {
            abort(403, 'Unauthorized action.');
        }   
    }
    
   /**
     * Show the form for editing the resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    
    public function batchEdit($id) {
        if (Gate::allows('manage-batch-contacts')) {
            $contacts = Contact::whereIn('id', explode(",", $id))->get();
            return view('admin.contact.batchEdit')
                            ->with('contacts', $contacts);
        } else {
            abort(403, 'Unauthorized action.');
        } 
    }
    /**
    * batch update resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Contact  $contact
    * @return \Illuminate\Http\Response
    **/
    public function batchUpdate(Request $request) {
        if (Gate::allows('manage-batch-contacts')) {
            $validator = $this->contacts->batchValidate($request->all(), true);
            
            if ($validator->fails()) {
                return response()->json(['error' => $validator->errors()], 401);
            }
            if ($this->contacts->batchUpdateContact($request->all()['contact'])){
                session()->flash('success', 'Data Has Been Updated Successfully');
                return response()->json(['success' => 'Data Has Been Inserted Successfully'], 201);
            } else {
                session()->flash('error', 'Nothing is changed to update');
                return response()->json(['errors' => 'Nothing is changed to update'], 500);
            }
            return response()->json([ 'errors' =>  'Server Not Found' ], 500);
        }else {
            abort(403, 'Unauthorized action.');
        } 
    }
    
    /**
     * Remove the batch resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    
    
    public function batchDelete(Request $request) {
        if (Gate::allows('manage-batch-contacts')) {
            $contactIds = $request->all()['contactIds'];
            if ($this->contacts->batchDeleteContact($contactIds)) {
                session()->flash('success', ' Data Is Deleted Successfully');
                return response()->json(['success' => 'Data Is Deleted Successfully'], 200);
            } else {
                session()->flash('error', 'Deleted Is Not Deleted Successfully');
                return response()->json(['error' => 'Deleted Is Not Deleted Successfully'], 200);
            }
        } else {
            abort(403, 'Unauthorized action.');
        } 
    }

}

resources/views/admin/contact/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif

            @if (session('error'))
            <div class="alert alert-danger" role="alert">
                {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif


            <div class="card">
                <div class="card-header">Contact List</div>
                <div class="card-body">
                    <div class="button-container text-right">

                        <!-- Button trigger modal -->
                        <!-- Button trigger modal -->
                        @canany(['manage-contacts','manage-batch-contacts'])
                        
                        <a href="{{route('admin.contacts.create')}}" data-action="{{route('admin.contacts.store')}}"  class="btn btn-sm btn-primary" id="singleCreate">
                            + Add New Contact 
                        </a>
                        @endcan
                        @can('manage-batch-contacts')
                        <a href="{{route('admin.batchcreate')}}" class="btn btn-sm btn-primary batch-create">
                            ++ Add New Contact Batch 
                        </a>
                        <a href="#" class="btn btn-sm btn-warning" id="batchUpdate">
                        Batch Update Contact  
                        </a>
                        <a href="#" class="btn btn-sm btn-danger" id="batchDelete">
                        Batch  Delete Contact
                        </a>
                        @endcan
                    </div>
                    <div class="text-right checkbox-button-container">
                        @canany(['manage-batch-contacts'])
                            <div class="custom-control custom-checkbox">
                                <input value="1" type="checkbox" class="custom-control-input" id="checkAllCheckBox">
                                <label class="custom-control-label" for="checkAllCheckBox">Check All</label>
                            </div>
                        @endcan
                    </div>
                    <div class="data-container">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scopr="col">#</th>
                                    <th scopr="col">Name</th>
                                    <th scopr="col">Email</th>
                                    <th scopr="col">Phone</th>
                                    <th scopr="col">City</th>
                                    <th scopr="col">Country</th>
                                    <th scopr="col">
                                        @canany(['manage-contacts', 'manage-batch-contacts'])
                                            Actions
                                        @endcan
                                    </th>

                                </tr>
                            </thead>
                            <tbody> 

                            @foreach($contacts as $contact)
                              
                                    <tr>
                                        <td socket="row"> {{$contact->id}} </td>
                                        <td> {{$contact->name}} </td>
                                        <td> {{$contact->email}} </td>
                                        <td> {{$contact->phone}} </td>
                                        <td> {{$contact->city}} </td>
                                        <td> {{$contact->country}} </td>
                                        <td class="text-right"> 
                                            @can('manage-batch-contacts')
                                                <div class="form-check float-left">              
                                                    <input name="edit[]" class="form-check-input batch-checkbox" type="checkbox" value="{{$contact->id}}" id="checkdelete{{$contact->id}}">
                                                    <label class="form-check-label" for="checkdelete{{$contact->id}}">
                                                    </label>
                                                </div>   
                                            @endcan     
                                                <a href="{{route('admin.contacts.show', $contact->id)}}" class="float-left btn btn-sm btn-primary">
                                                    view
                                                </a>                   
                                            @can('manage-contacts')
                                                <a data-contact="{{$contact}}" data-action="{{route('admin.contacts.update', $contact->id)}}" href="{{route('admin.contacts.edit', $contact->id)}}" class="btn btn-sm btn-warning edit-button float-left">
                                                    Edit
                                                </a>
                                            @endcan
                                            @can('manage-contacts')
                                                <form action="{{route('admin.contacts.destroy', $contact->id)}}" method="post"  class="float-left delete-button">
                                                    @csrf 
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" type="button" class="btn btn-sm btn-danger">Delete</button>
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                         
                            @endforeach
                            </tbody>
                        </table>
                        <div class="">
                            
                        </div>
                    </div>
                </div>
                <div class="card-footer clearfix">
                        <div class="float-right">
                         {{ $contacts->links() }}
                        
                        </div>
                    
                 </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Edit Modal -->

<div class="modal fade" id="singleModal" tabindex="-1" role="dialog" aria-labelledby="singleModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{{route('admin.contacts.store')}}" method="POST">
                @csrf
                <div id="update-field"></div>
                
                <div class="modal-header">
                    <h5 class="modal-title" id="singleModalTitle"> </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group row">
                        <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }}</label>
                        <div class="col-md-8">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-3 col-form-label text-md-right">Email </label>
                        <div class="col-md-8">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-md-3 col-form-label text-md-right">Mobile </label>
                        <div class="col-md-8">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" required autocomplete="phone">                         
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>                         
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="city" class="col-md-3 col-form-label text-md-right">City </label>
                        <div class="col-md-8">
                            <input id="city" type="text" class="form-control @error('city') is-invalid @enderror" name="city" value="{{ old('city') }}" required autocomplete="city">
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>                       
                    <div class="form-group row">
                        <label for="city" class="col-md-3 col-form-label text-md-right">Country </label>
                        <div class="col-md-8">
                            <input id="country" type="text" class="form-control @error('country') is-invalid @enderror" name="country" value="{{ old('contry') }}" required autocomplete="country">

                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
               
                        </div>
                    </div>                  


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button  id="saveContact"  type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- End Edit Modal -->

@endsection

resources/views/admin/contact/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
           
            
            <div class="card">
                <div class="card-header">
                     
                <div class="row">
                    <div class="col-md-4">Contact</div>
                    <div  class="col-md-8 text-right">
                        <a class="btn btn-primary" href="{{route('admin.contacts.index')}}"> View All Contact </a>
                        <a class="btn btn-warning" href="{{route('admin.contacts.edit', $contact->id)}}"> Edit This Contact </a>
                    </div>
                </div>
                
                </div>
                <div class="card-body">


                    @csrf
                    {{ method_field('PUT') }}
                    <input type="hidden" name="id" value="{{ $contact->id }}">
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control"  name="name" value="{{ $contact->name }}" readonly >

                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">Email </label>
                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" value="{{ $contact->email }}" readonly>


                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Mobile </label>
                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" value="{{ $contact->phone }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="city" class="col-md-4 col-form-label text-md-right">City </label>
                        <div class="col-md-6">
                            <input id="city" type="text" class="form-control" name="city" value="{{ $contact->city }}" readonly>


                        </div>
                    </div>                       
                    <div class="form-group row">
                        <label for="city" class="col-md-4 col-form-label text-md-right">Country </label>
                        <div class="col-md-6">
                            <input id="country" type="text" class="form-control" name="country" value="{{ $contact->country }}" readonly>
                        </div>
                    </div>                  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection