routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
        Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
        Route::resource('/contacts', 'ContactsController');
        
        Route::get('/batchcreate/{rows}', 'ContactsController@batchCreate')->name('batchcreate');
        Route::post('/batchcreate', 'ContactsController@batchStore')->name('batchcreate');
        
        Route::get('/batchupdate/{id}', 'ContactsController@batchEdit')->name('batchupdate');
        Route::post('/batchupdate', 'ContactsController@batchUpdate')->name('batchupdate');        
        
        Route::delete('/batchdelete', 'ContactsController@batchDelete')->name('batchdelete');
        
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Laravel\Passport\Passport;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function roles() {
        return $this->belongsToMany('App\Role');
    }
    
    public function hasAnyRoles($roles) {
        if($this->roles()->whereIn('name', $roles)->first()){
            return true;
        }
        return false;
    }
    public function hasRole($role) {
        if($this->roles()->where('name', $role)->first()){
            return true;
        }
        return false;
    }
    public function AauthAcessToken(){
        return $this->hasMany('\App\OauthAccessToken');
    }
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth; 
use Illuminate\Http\Request;
use Validator;
use App\User;
use Gate;
use Cookie;
class UserController extends Controller {

    /**
     * Api success status
     * */
    public $successStatus = 200;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return User::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user) {
        //
    }

    /**
     * login api 
     * 
     * @return \Illuminate\Http\Response 
     */
    public function login(Request $request) {
        $validator = Validator::make($request->all(), [
                    'email' => 'required|email',
                    'password' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 401);
        }
        if (Auth::attempt(['email' => request('email'), 'password' => request('password')])) {
            $user = Auth::user();
            $success['token'] = $user->createToken('MyApp')->accessToken;
            return response()->json(['success' => $success], $this->successStatus);
        } else {
            return response()->json(['error' => 'Unauthorised'], 401);
        }
    }

    /**
     * Register api 
     * 
     * @return \Illuminate\Http\Response 
     */
    public function register(Request $request) {
        $validator = Validator::make($request->all(), [
                    'name' => 'required',
                    'email' => 'required|email',
                    'password' => 'required',
                    'c_password' => 'required|same:password',
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 401);
        }
        $input = $request->all();
        $input['password'] = bcrypt($input['password']);
        $user = User::create($input);
        $success['token'] = $user->createToken('MyApp')->accessToken;
        $success['name'] = $user->name;
        return response()->json(['success' => $success], $this->successStatus);
    }

    /**
     * 
     * API Logout 
     * 
     * **/

    public function logoutApi(Request $request){
        auth('web')->logout();
        $success = "Successfully log out";
        return response()->json(['message' => $success], $this->successStatus);    
    }

    /**
     * details api 
     * 
     * @return \Illuminate\Http\Response 
     */
    public function details() {
        $user = Auth::user();
        return response()->json(['success' => $user], $this->successStatus);
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Role;
use Gate;

class UsersController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $users = User::all();
        $roles = Role::all();
        $data = ['users' => $users, 'roles' => $roles];
        return view('admin.users.index')
                        ->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        if (Gate::denies('edit-users')) {
            return redirect(route('admin.users.index'));
        }
        $roles = Role::all();
        $data = ['user' => $user, 'roles' => $roles];
        return view('admin.users.edit')
                        ->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user) {
        $user->roles()->sync($request->roles);
        $user->name = $request->name;
        $user->email = $request->email;

        if ($user->save()) {
            $request->session()->flash('success', $user->name . ' Has been updated ');
        } else {
            $request->session()->flash('error', 'Testing error flash message');
        }
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user) {
        if (Gate::denies('delete-users')) {
            return redirect(route('admin.users.index'));
        }
        $user->roles()->detach();
        $user->delete();
        return redirect()->route('admin.users.index');
    }

    



}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit User {{$user->name}} </div>
                <div class="card-body">
                 
                <form action="{{route('admin.users.update', $user->id)}}" method="POST">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right"> User Role </label>
                            <div class="col-md-6">
                            @foreach($roles as $role)

                                <div class="form-check">
                                  <input name='roles[]' value="{{$role->id}}" type="checkbox" class="form-check-input" id="checkBox{{$role->id}}"
                                  @if($user->roles->pluck('id')->contains($role->id)) checked @endif >
                                  <label class="form-check-label" for="checkBox{{$role->id}}">{{ucfirst($role->name)}}</label>
                                </div>
                            @endforeach
                            </div>
                        </div>
                    <div class="form-group">
                        <label for="email" class="col-md-4 col-form-label text-md-right"> 
                        <button type="submit" class="btn btn-sm btn-warning"> Update </button>
                        </label>
                        
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif

            @if (session('error'))
            <div class="alert alert-danger" role="alert">
                {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif
            <div class="card">
                <div class="card-header">Contact List</div>
                <div class="card-body">

                    <table class="table">
                        <thead>
                            <tr>
                                <th scopr="col">#</th>
                                <th scopr="col">Name</th>
                                <th scopr="col">Email</th>
                                <th scopr="col">Roles</th>

                                <th scopr="col">
                                    @canany(['edit-users','delete-users'])
                                    Actions
                                    @endcan
                                </th>

                            </tr>
                        </thead>
                        <tbody> 
                            @foreach($users as $user)
                            <tr>
                                <td socket="row"> {{$user->id}} </td>
                                <td> {{$user->name}} </td>
                                <td> {{$user->email}} </td>
                                <td>
                                    {{implode(',',$user->roles()->get()->pluck('name')->toArray())}} 
                                </td>
                                <td> 
                                    @can('edit-users')
                                    <a data-user="{{$user}}" data-role="{{$user->roles}}" data-action="{{route('admin.users.update', $user->id)}}"   href="{{route('admin.users.edit', $user->id)}}" class="btn btn-sm btn-warning edit-user-button float-left">
                                        Edit
                                    </a>
                                    @endcan
                                    @can('delete-users')
                                    <form action="{{route('admin.users.destroy', $user->id)}}" method="post"  class="float-left">
                                        @csrf 
                                        {{ method_field('DELETE') }}
                                        <button type="submit" type="button" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>             
                    </table> 
                </div>
                <div class="card-footer"> </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Edit Modal -->

<div class="modal fade" id="singleModal" tabindex="-1" role="dialog" aria-labelledby="singleModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action=" {{route('admin.users.update', $user->id)}}" method="POST">
                @csrf
                <div id="update-field"></div>

                <div class="modal-header">
                    <h5 class="modal-title" id="singleModalTitle"> </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @csrf
                    {{ method_field('PUT') }}
                    <input id="userId" type="hidden" name="id" value="">
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right"> Name </label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="" required autocomplete="email">
                            <span class="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right"> User Role </label>
                        <div class="col-md-6">
                            @foreach($roles as $role)
                            <div class="form-check">
                                <input name='roles[]' value="{{$role->id}}" type="checkbox" class="form-check-input" id="checkBox{{$role->id}}">
                                <label class="form-check-label" for="checkBox{{$role->id}}">{{ucfirst($role->name)}}</label>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="saveUser" type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- End Edit Modal -->

@endsection